// Generated from Checkbox normalized contract IR. Do not hand-edit.
use std::collections::BTreeMap;
use gpui::{prelude::*,div,Context,SharedString,Window,FocusHandle,EventEmitter,MouseButton,Subscription};
use crate::control::{BooleanState,ChangeRequest};
use crate::style::{StyleRule,StyleCondition,StyleDeclaration,StyleState,Theme,ResolvedPartStyle,StyleError,resolve_part_style,apply_part_style,apply_interaction_style,render_pseudo};
pub struct Checkbox{pub state:BooleanState,pub hovered:bool,pub active:bool,_focus_subscriptions:Vec<Subscription>,pub label:SharedString,pub theme:Theme,pub focused:bool,pub variant_values:BTreeMap<&'static str,SharedString>,pub focus_handle:Option<FocusHandle>,pub indeterminate:bool,}
impl Default for Checkbox{fn default()->Self {let mut variants=BTreeMap::new();variants.insert("size","md".into());let mut state=BooleanState::new(false);state.disabled=false;Self{state,hovered:false,active:false,_focus_subscriptions:Vec::new(),label:SharedString::default(),theme:Theme::default(),focused:false,variant_values:variants,focus_handle:None,indeterminate:false,}}}
impl Checkbox{
 pub const STYLE_RULES:&'static [StyleRule]=&[StyleRule {part:"root",conditions:&[],declarations:&[StyleDeclaration {property:"box-model.padding",value:"0",token:None},StyleDeclaration {property:"box-model.padding-block",value:"0",token:None},StyleDeclaration {property:"box-model.padding-block-start",value:"4px",token:Some("semantic.input.size.medium.padding-block")},StyleDeclaration {property:"box-model.padding-block-end",value:"4px",token:Some("semantic.input.size.medium.padding-block")},StyleDeclaration {property:"box-model.padding-inline",value:"0",token:None},StyleDeclaration {property:"box-model.padding-inline-start",value:"8px",token:Some("semantic.input.size.medium.padding-inline")},StyleDeclaration {property:"box-model.padding-inline-end",value:"8px",token:Some("semantic.input.size.medium.padding-inline")},StyleDeclaration {property:"box-model.gap",value:"8px",token:Some("semantic.input.size.medium.gap")},StyleDeclaration {property:"box-model.width",value:"auto",token:None},StyleDeclaration {property:"box-model.min-width",value:"0",token:None},StyleDeclaration {property:"box-model.max-width",value:"none",token:None},StyleDeclaration {property:"box-model.height",value:"auto",token:None},StyleDeclaration {property:"box-model.min-height",value:"32px",token:Some("semantic.input.size.medium.min-height")},StyleDeclaration {property:"box-model.max-height",value:"none",token:None},StyleDeclaration {property:"checkbox.color.background",value:"#ffffff",token:Some("semantic.color.background.primary")},StyleDeclaration {property:"checkbox.color.border",value:"#a0a0a1",token:Some("semantic.color.border.default")},StyleDeclaration {property:"checkbox.border.width",value:"1px",token:Some("semantic.shape.control.border.defaultWidth")},StyleDeclaration {property:"checkbox.border.radius",value:"4px",token:Some("semantic.shape.radius.small")},StyleDeclaration {property:"checkbox.transition.duration",value:"150ms",token:Some("core.motion.duration.short")},StyleDeclaration {property:"checkbox.focus.ring.width",value:"2px",token:Some("semantic.focus.ring.width")},StyleDeclaration {property:"checkbox.focus.ring.color",value:"#0566fe",token:Some("semantic.focus.ring.color")},StyleDeclaration {property:"checkbox.focus.ring.style",value:"solid",token:Some("semantic.focus.ring.style")},StyleDeclaration {property:"checkbox.focus.ring.offset",value:"2px",token:Some("semantic.focus.ring.offset")},StyleDeclaration {property:"checkbox.color.mark",value:"#ffffff",token:Some("semantic.color.foreground.on.brand")}]},
StyleRule {part:"root",conditions:&[],declarations:&[StyleDeclaration {property:"padding",value:"0",token:Some("box-model.padding")},StyleDeclaration {property:"padding-block",value:"0",token:Some("box-model.padding-block")},StyleDeclaration {property:"padding-block-start",value:"4px",token:Some("box-model.padding-block-start")},StyleDeclaration {property:"padding-block-end",value:"4px",token:Some("box-model.padding-block-end")},StyleDeclaration {property:"padding-inline",value:"0",token:Some("box-model.padding-inline")},StyleDeclaration {property:"padding-inline-start",value:"8px",token:Some("box-model.padding-inline-start")},StyleDeclaration {property:"padding-inline-end",value:"8px",token:Some("box-model.padding-inline-end")},StyleDeclaration {property:"gap",value:"8px",token:Some("box-model.gap")},StyleDeclaration {property:"min-width",value:"0",token:Some("box-model.min-width")},StyleDeclaration {property:"min-height",value:"32px",token:Some("box-model.min-height")}]},
StyleRule {part:"root",conditions:&[],declarations:&[StyleDeclaration {property:"display",value:"inline-flex",token:None},StyleDeclaration {property:"align-items",value:"center",token:None}]},
StyleRule {part:"indicator",conditions:&[StyleCondition::Hover],declarations:&[StyleDeclaration {property:"checkbox.color.border",value:"#888889",token:Some("semantic.color.border.hover")}]},
StyleRule {part:"input",conditions:&[],declarations:&[StyleDeclaration {property:"position",value:"absolute",token:None},StyleDeclaration {property:"width",value:"1px",token:None},StyleDeclaration {property:"height",value:"1px",token:None},StyleDeclaration {property:"checkbox.design.input.spacing.padding",value:"0",token:None},StyleDeclaration {property:"padding",value:"0",token:Some("checkbox.design.input.spacing.padding")},StyleDeclaration {property:"margin",value:"-1px",token:None},StyleDeclaration {property:"overflow",value:"hidden",token:None},StyleDeclaration {property:"white-space",value:"nowrap",token:None}]},
StyleRule {part:"indicator",conditions:&[],declarations:&[StyleDeclaration {property:"display",value:"inline-block",token:None},StyleDeclaration {property:"position",value:"relative",token:None},StyleDeclaration {property:"width",value:"16px",token:None},StyleDeclaration {property:"height",value:"16px",token:None},StyleDeclaration {property:"checkbox.design.indicator.shape.radius",value:"4px",token:Some("checkbox.border.radius")},StyleDeclaration {property:"border-radius",value:"4px",token:Some("checkbox.design.indicator.shape.radius")},StyleDeclaration {property:"checkbox.design.indicator.border.color",value:"#a0a0a1",token:Some("checkbox.color.border")},StyleDeclaration {property:"border-color",value:"#a0a0a1",token:Some("checkbox.design.indicator.border.color")},StyleDeclaration {property:"checkbox.design.indicator.background.fill",value:"#ffffff",token:Some("checkbox.color.background")},StyleDeclaration {property:"background-color",value:"#ffffff",token:Some("checkbox.design.indicator.background.fill")},StyleDeclaration {property:"checkbox.design.indicator.border.style",value:"solid",token:None},StyleDeclaration {property:"border-style",value:"solid",token:Some("checkbox.design.indicator.border.style")},StyleDeclaration {property:"checkbox.design.indicator.border.width",value:"1px",token:Some("checkbox.border.width")},StyleDeclaration {property:"border-width",value:"1px",token:Some("checkbox.design.indicator.border.width")},StyleDeclaration {property:"box-sizing",value:"border-box",token:None}]},
StyleRule {part:"indicator",conditions:&[StyleCondition::Checked(true)],declarations:&[StyleDeclaration {property:"checkbox.color.background",value:"#0566fe",token:Some("semantic.color.action.background.primary.default")}]},
StyleRule {part:"indicator",conditions:&[StyleCondition::Focus],declarations:&[StyleDeclaration {property:"checkbox.design.condition-0c6bee9c3217.focus.width",value:"2px",token:Some("checkbox.focus.ring.width")},StyleDeclaration {property:"outline-width",value:"2px",token:Some("checkbox.design.condition-0c6bee9c3217.focus.width")},StyleDeclaration {property:"checkbox.design.condition-0c6bee9c3217.focus.color",value:"#0566fe",token:Some("checkbox.focus.ring.color")},StyleDeclaration {property:"outline-color",value:"#0566fe",token:Some("checkbox.design.condition-0c6bee9c3217.focus.color")},StyleDeclaration {property:"checkbox.design.condition-0c6bee9c3217.focus.style",value:"solid",token:Some("checkbox.focus.ring.style")},StyleDeclaration {property:"outline-style",value:"solid",token:Some("checkbox.design.condition-0c6bee9c3217.focus.style")},StyleDeclaration {property:"checkbox.design.condition-0c6bee9c3217.focus.offset",value:"2px",token:Some("checkbox.focus.ring.offset")},StyleDeclaration {property:"outline-offset",value:"2px",token:Some("checkbox.design.condition-0c6bee9c3217.focus.offset")}]},
StyleRule {part:"indicator::after",conditions:&[],declarations:&[StyleDeclaration {property:"position",value:"absolute",token:None},StyleDeclaration {property:"top",value:"50%",token:None},StyleDeclaration {property:"left",value:"50%",token:None},StyleDeclaration {property:"checkbox.design.condition-c8a599f99e6e.appearance.opacity",value:"0",token:None},StyleDeclaration {property:"opacity",value:"0",token:Some("checkbox.design.condition-c8a599f99e6e.appearance.opacity")},StyleDeclaration {property:"box-sizing",value:"border-box",token:None},StyleDeclaration {property:"checkbox.design.condition-c8a599f99e6e.border.color",value:"#ffffff",token:Some("checkbox.color.mark")},StyleDeclaration {property:"border-color",value:"#ffffff",token:Some("checkbox.design.condition-c8a599f99e6e.border.color")}]},
StyleRule {part:"indicator::after",conditions:&[StyleCondition::Checked(true)],declarations:&[StyleDeclaration {property:"width",value:"5px",token:None},StyleDeclaration {property:"height",value:"9px",token:None},StyleDeclaration {property:"checkbox.design.condition-94add815057f.border.style",value:"solid",token:None},StyleDeclaration {property:"border-style",value:"solid",token:Some("checkbox.design.condition-94add815057f.border.style")},StyleDeclaration {property:"checkbox.design.condition-94add815057f.border.width",value:"0 2px 2px 0",token:None},StyleDeclaration {property:"border-width",value:"0 2px 2px 0",token:Some("checkbox.design.condition-94add815057f.border.width")},StyleDeclaration {property:"transform",value:"translate(-50%, -65%) rotate(45deg)",token:None},StyleDeclaration {property:"checkbox.design.condition-94add815057f.appearance.opacity",value:"1",token:None},StyleDeclaration {property:"opacity",value:"1",token:Some("checkbox.design.condition-94add815057f.appearance.opacity")}]},
StyleRule {part:"indicator",conditions:&[StyleCondition::Indeterminate(true)],declarations:&[StyleDeclaration {property:"checkbox.color.background",value:"#0566fe",token:Some("semantic.color.action.background.primary.default")}]},
StyleRule {part:"indicator::after",conditions:&[StyleCondition::Indeterminate(true)],declarations:&[StyleDeclaration {property:"width",value:"8px",token:None},StyleDeclaration {property:"height",value:"2px",token:None},StyleDeclaration {property:"checkbox.design.condition-b54308f8dcd4.border.width",value:"0",token:None},StyleDeclaration {property:"border-width",value:"0",token:Some("checkbox.design.condition-b54308f8dcd4.border.width")},StyleDeclaration {property:"checkbox.design.condition-b54308f8dcd4.background.fill",value:"#ffffff",token:Some("checkbox.color.mark")},StyleDeclaration {property:"background-color",value:"#ffffff",token:Some("checkbox.design.condition-b54308f8dcd4.background.fill")},StyleDeclaration {property:"transform",value:"translate(-50%, -50%)",token:None},StyleDeclaration {property:"checkbox.design.condition-b54308f8dcd4.appearance.opacity",value:"1",token:None},StyleDeclaration {property:"opacity",value:"1",token:Some("checkbox.design.condition-b54308f8dcd4.appearance.opacity")}]},
StyleRule {part:"indicator",conditions:&[StyleCondition::Disabled(true)],declarations:&[StyleDeclaration {property:"checkbox.color.background",value:"#d0d0d0",token:Some("semantic.color.background.disabled")},StyleDeclaration {property:"checkbox.color.mark",value:"#727272",token:Some("semantic.color.foreground.disabled")}]}];
 pub fn label(mut self,value:impl Into<SharedString>)->Self{self.label=value.into();self}
 pub fn set_label(&mut self,value:impl Into<SharedString>,cx:&mut Context<Self>){self.label=value.into();cx.notify();}
 pub fn theme(mut self,value:Theme)->Self{self.theme=value;self}
 pub fn set_theme(&mut self,value:Theme,cx:&mut Context<Self>){self.theme=value;cx.notify();}
 pub fn resolved_style(&self,part:&str)->Result<ResolvedPartStyle,StyleError>{
  let variants:Vec<(&str,&str)>=self.variant_values.iter().map(|(axis,value)|(*axis,value.as_ref())).collect();
  let state=StyleState{variants:&variants,checked:self.state.value(),disabled:self.state.disabled,indeterminate:self.indeterminate,hovered:self.hovered,active:self.active,focused:self.focused};
  resolve_part_style(part,Self::STYLE_RULES,&state,&self.theme)
 }
 pub fn size(mut self,value:impl Into<SharedString>)->Self {let value=value.into();assert!(["sm","md","lg"].contains(&value.as_ref()),"unsupported size variant");self.variant_values.insert("size",value);self}
pub fn set_size(&mut self,value:impl Into<SharedString>,cx:&mut Context<Self>){let value=value.into();assert!(["sm","md","lg"].contains(&value.as_ref()),"unsupported size variant");self.variant_values.insert("size",value);cx.notify();}
pub fn indeterminate(mut self,value:bool)->Self {self.indeterminate=value;self}
pub fn set_indeterminate(&mut self,value:bool,cx:&mut Context<Self>){self.indeterminate=value;cx.notify();}

 pub const CHANNEL:&'static str="checked";
 pub const CHANGE_HANDLER:&'static str="onChange";
 pub const CONTROL_PART:&'static str="input";
 pub const ACTIVATION_KEYS:&'static [&'static str]=&["space"];
 pub fn checked(mut self,value:Option<bool>)->Self {self.state.controlled=value;self}
 pub fn set_checked(&mut self,value:Option<bool>,cx:&mut Context<Self>){self.state.controlled=value;cx.notify();}
 pub fn default_checked(mut self,value:bool)->Self {let controlled=self.state.controlled;let disabled=self.state.disabled;self.state=BooleanState::new(value);self.state.controlled=controlled;self.state.disabled=disabled;self}
 pub fn disabled(mut self,value:bool)->Self {self.state.disabled=value;self}
pub fn set_disabled(&mut self,value:bool,cx:&mut Context<Self>){self.state.disabled=value;cx.notify();}
 pub fn request_change(&mut self)->Option<ChangeRequest>{self.state.request_toggle().map(|value|ChangeRequest{channel:Self::CHANNEL,handler:Self::CHANGE_HANDLER,value})}
 pub fn request_key(&mut self,key:&str)->Option<ChangeRequest>{if Self::ACTIVATION_KEYS.contains(&key){self.request_change()}else{None}}

}
impl EventEmitter<ChangeRequest> for Checkbox{}
impl Render for Checkbox{fn render(&mut self,window:&mut Window,cx:&mut Context<Self>)->impl IntoElement{
 if self.focus_handle.is_none(){let handle=cx.focus_handle();self._focus_subscriptions.push(cx.on_focus(&handle,window,|_,_,cx|cx.notify()));self._focus_subscriptions.push(cx.on_blur(&handle,window,|_,_,cx|cx.notify()));self.focus_handle=Some(handle);}self.focus_handle=self.focus_handle.take().map(|handle|handle.tab_index(0).tab_stop(!self.state.disabled));
 let variants:Vec<(&str,&str)>=self.variant_values.iter().map(|(axis,value)|(*axis,value.as_ref())).collect();
 self.theme.rem_size_px=f32::from(window.rem_size());self.theme.inherited_font_size_px=f32::from(window.text_style().font_size.to_pixels(window.rem_size()));let theme=self.theme.clone();
 self.focused=self.focus_handle.as_ref().map(|handle|handle.is_focused(window)).unwrap_or(false);
 let style_state=StyleState{variants:&variants,checked:self.state.value(),disabled:self.state.disabled,indeterminate:self.indeterminate,hovered:self.hovered,active:self.active,focused:self.focused};
 let root=apply_part_style(div(),"root",Self::STYLE_RULES,&style_state,&theme).debug_selector(||"checkbox-root".to_string()).child(apply_part_style(div(),"indicator",Self::STYLE_RULES,&style_state,&theme).debug_selector(||"checkbox-indicator".to_string()).child(render_pseudo("indicator::after",Self::STYLE_RULES,&style_state,&theme))).when(!self.label.is_empty(),|node|node.child(div().debug_selector(||"checkbox-label".to_string()).child(self.label.clone()))).id("checkbox");
 let root=apply_interaction_style(root,"root",Self::STYLE_RULES,&style_state,&theme);
 let root=root.track_focus(self.focus_handle.as_ref().unwrap()).tab_index(0).tab_stop(!self.state.disabled).on_hover(cx.listener(|this,hovered,_,cx|{this.hovered=*hovered;cx.notify();})).on_mouse_down(MouseButton::Left,cx.listener(|this,_,window,cx|{if !this.state.disabled {this.active=true;window.focus(this.focus_handle.as_ref().unwrap());cx.notify();}})).on_mouse_up(MouseButton::Left,cx.listener(|this,_,_,cx|{this.active=false;cx.notify();})).on_mouse_up_out(MouseButton::Left,cx.listener(|this,_,_,cx|{this.active=false;cx.notify();})).on_click(cx.listener(|this,_,_,cx|{if let Some(request)=this.request_change(){cx.emit(request);cx.notify();}})).on_key_down(cx.listener(|this,event,_,cx|{if crate::view::is_activation_key(event,Self::ACTIVATION_KEYS.contains(&"enter")){if let Some(request)=this.request_change(){cx.emit(request);cx.notify();cx.stop_propagation();}}}));
 root
}}
