// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { ref } from 'lit/directives/ref.js';
import { PagedSetController } from "../../primitives/controllers/PagingController.js";
import { property } from 'lit/decorators.js';
import '../Button/Button.js';
import '../Icon/Icon.js';
import '../Input/Input.js';
import '../Pagination/Pagination.js';
import { PageNavigatorBehavior } from './PageNavigatorBehavior.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type PageNavigatorPresentation = "indicators" | "pages";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class PageNavigatorElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    @layer components.defaults {
    .page-navigator {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-page-navigator-design-root-spacing-gap, 8px);
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      display: flex;
      align-items: center;
      flex-wrap: wrap;
    }

    .page-navigator__field {
      width: var(--fsds-page-navigator-design-field-sizing-width, 64px);
    }

    .page-navigator__input {
      width: var(--fsds-page-navigator-design-input-sizing-width, 100%);
    }

    .page-navigator__total {
      font-variant-numeric: tabular-nums;
    }
    }
  `;

  @property({ attribute: false }) pages?: string[] = [];
  @property({ type: Number }) index?: number;
  @property({ type: Number }) defaultIndex?: number = 0;
  @property({ attribute: false }) onIndexChange?: (index: number) => void;
  @property({ type: String }) presentation?: PageNavigatorPresentation = "indicators";
  @property({ type: String }) label?: string = "Page navigation";
  @property({ type: Boolean }) disabled?: boolean = false;
  @property({ type: Number }) pageCount?: number;
  @property({ type: String }) pageLabel?: string = "Current page";
  @property({ type: String }) previousLabel?: string = "Previous page";
  @property({ type: String }) nextLabel?: string = "Next page";
  @property({ type: String }) ofLabel?: string = "of";
  @property({ type: String }) commitLabel?: string = "Go";
  @property({ type: Boolean }) showChoices?: boolean = false;

  private initializedBehavior?: PageNavigatorBehavior;
  private get behavior(): PageNavigatorBehavior {
    return this.initializedBehavior ??= new PageNavigatorBehavior(this, {
    index: () => this.index,
    defaultIndex: this.defaultIndex,
    onIndexChange: (v) => this.onIndexChange?.(v),
  });
  }
  private pagedSet = new PagedSetController(this, () => ({ index: this.behavior.page, items: this.pages ?? [],
    count: this.pageCount, disabled: this.disabled, onIndexChange: (value) => this.behavior.setPage(value) }));

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "page-navigator");
  }

  private computeClasses(): string {
    return [
      "page-navigator",
      (this.disabled ?? false) ? "page-navigator--disabled" : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}" role="group" aria-label=${ifDefined((this.label ?? "Page navigation"))} data-fsds-box="">
  <fsds-button class=${'page-navigator__previous'} type="button" .onClick=${this.pagedSet.previous} .disabled=${this.pagedSet.state.previousDisabled} .ariaLabel=${(this.previousLabel ?? "Previous page")}>
    <fsds-icon class=${'page-navigator__previousIcon'} name="arrow-left" size="sm"></fsds-icon>
  </fsds-button>
  <div class=${'page-navigator__field'} @keydown=${this.pagedSet.commitOnEnter} @focusout=${this.pagedSet.commit}>
    <fsds-input class=${'page-navigator__input'} type="number" .onChange=${this.pagedSet.edit} .value=${this.pagedSet.state.draft} .disabled=${this.pagedSet.state.disabled} .ariaLabel=${(this.pageLabel ?? "Current page")}></fsds-input>
  </div>
  <span class=${'page-navigator__context'}>${(this.ofLabel ?? "of")}</span>
  <span class=${'page-navigator__total'}>${this.pagedSet.state.count}</span>
  <fsds-button class=${'page-navigator__commit'} type="button" .onClick=${this.pagedSet.commit} .disabled=${this.pagedSet.state.disabled} .ariaLabel=${(this.commitLabel ?? "Go")}>
    <span>${(this.commitLabel ?? "Go")}</span>
  </fsds-button>
  <fsds-button class=${'page-navigator__next'} type="button" .onClick=${this.pagedSet.next} .disabled=${this.pagedSet.state.nextDisabled} .ariaLabel=${(this.nextLabel ?? "Next page")}>
    <fsds-icon class=${'page-navigator__nextIcon'} name="arrow-right" size="sm"></fsds-icon>
  </fsds-button>
  ${this.showChoices ? html`
  <fsds-pagination class=${'page-navigator__choices'} .onIndexChange=${this.pagedSet.request} .pages=${(this.pages ?? [])} .index=${this.behavior.page} .presentation=${(this.presentation ?? "indicators")} .label=${(this.label ?? "Page navigation")} .disabled=${this.pagedSet.state.disabled}></fsds-pagination>
  ` : nothing}
</div>`;
  }
}

customElements.define('fsds-page-navigator', PageNavigatorElement);

// @generated:end

// @custom:start trailing

// @custom:end