// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { FieldBehavior } from './FieldBehavior.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type FieldStatus = "idle" | "validating" | "valid" | "invalid";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class FieldElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .field {
      --fsds-field-gap-y: var(--fsds-semantic-spacing-density-compact-sm, 8px);
      --fsds-field-gap-meta: var(--fsds-core-spacing-size-03, 4px);
      --fsds-field-color-fg: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-field-color-invalid-text: var(--fsds-semantic-color-foreground-danger, #d92d2e);
      --fsds-field-label-font-size: var(--fsds-semantic-typography-body-small-font-size, 14px);
      --fsds-field-label-color: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .field--idle {
      --fsds-field-color-fg: var(--fsds-semantic-color-foreground-primary, #141414);
    }

    .field--validating {
      --fsds-field-color-fg: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .field--valid {
      --fsds-field-color-fg: var(--fsds-semantic-color-foreground-success, #497f21);
    }

    .field--invalid {
      --fsds-field-color-fg: var(--fsds-semantic-color-foreground-danger, #d92d2e);
    }

    @layer components.defaults {
    .field {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-field-design-root-spacing-gap, var(--fsds-field-gap-y, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      display: flex;
      flex-direction: column;
    }

    .field__label {
      display: inline-block;
      font-size: var(--fsds-field-design-label-typography-size, var(--fsds-field-label-font-size, 14px));
      font-weight: var(--fsds-field-design-label-typography-weight, 500);
      color: var(--fsds-field-design-label-foreground-color, var(--fsds-field-label-color, #474647));
    }

    .field__header {
      display: flex;
      align-items: baseline;
      justify-content: space-between;
      gap: var(--fsds-field-design-header-spacing-gap, var(--fsds-field-gap-meta, 4px));
    }

    .field__control {
      display: flex;
      flex-direction: column;
      width: 100%;
      box-sizing: border-box;
    }

    .field__help {
      display: block;
      font-size: var(--fsds-field-design-help-typography-size, 0.875em);
      color: var(--fsds-field-design-help-foreground-color, var(--fsds-field-color-fg, #141414));
    }

    .field__error {
      display: block;
      font-size: var(--fsds-field-design-error-typography-size, 0.875em);
      color: var(--fsds-field-design-error-foreground-color, var(--fsds-field-color-invalid-text, #d92d2e));
    }

    .field__meta {
      display: flex;
      flex-direction: column;
      gap: var(--fsds-field-design-meta-spacing-gap, var(--fsds-field-gap-meta, 4px));
    }

    .field__validatingIndicator {
      display: inline-flex;
      width: 1em;
      height: 1em;
      color: var(--fsds-field-design-validating-indicator-foreground-color, var(--fsds-field-color-fg, #141414));
    }

    .field--disabled .field__header, .field--disabled .field__meta {
      opacity: 0.5;
    }
    }
  `;

  @property({ type: String }) name!: string;
  @property({ type: Boolean }) required?: boolean;
  @property({ type: Boolean }) disabled?: boolean;
  @property({ type: Boolean }) readOnly?: boolean;
  @property({ type: String }) value?: string;
  @property({ type: String }) defaultValue?: string;
  @property({ attribute: false }) onChange?: (value: string) => void;
  @property({ attribute: false }) validate?: ((value: string, context: { name: string; touched: boolean; dirty: boolean }) => string | string[] | null | Promise<string | string[] | null>);
  @property({ type: String }) status?: FieldStatus;
  @property({ type: Boolean }) validating?: boolean;

  private initializedBehavior?: FieldBehavior;
  private get behavior(): FieldBehavior {
    return this.initializedBehavior ??= new FieldBehavior(this, {
    value: () => this.value,
    defaultValue: this.defaultValue,
    onChange: (v) => this.onChange?.(v),
  });
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "field");
  }

  private computeClasses(): string {
    return [
      "field",
      this.status ? `field--${this.status}` : null,
      this.disabled ? "field--disabled" : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}" role="group" aria-labelledby=${ifDefined([this.querySelector('[slot="label"]') !== null ? 'field-label' : null].filter(Boolean).join(' ') || undefined)} data-fsds-box="">
  <div class=${'field__header'}>
    <label class=${'field__label'} id="field-label">
      <slot name="label" @slotchange=${() => this.requestUpdate()}></slot>
    </label>
  </div>
  <div class=${'field__control'}>
    <slot name="control"></slot>
  </div>
  <div class=${'field__meta'}>
    <span class=${'field__help'} id="field-help">
      <slot name="help"></slot>
    </span>
    <span class=${'field__error'} id="field-error">
      <slot name="error"></slot>
    </span>
    ${this.validating ? html`
    <span class=${'field__validatingIndicator'}>
      <slot name="validatingIndicator"></slot>
    </span>
    ` : nothing}
  </div>
</div>`;
  }
}

customElements.define('fsds-field', FieldElement);


export class FieldHeaderElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .field {
      --fsds-field-gap-y: var(--fsds-semantic-spacing-density-compact-sm, 8px);
      --fsds-field-gap-meta: var(--fsds-core-spacing-size-03, 4px);
      --fsds-field-color-fg: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-field-color-invalid-text: var(--fsds-semantic-color-foreground-danger, #d92d2e);
      --fsds-field-label-font-size: var(--fsds-semantic-typography-body-small-font-size, 14px);
      --fsds-field-label-color: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .field--idle {
      --fsds-field-color-fg: var(--fsds-semantic-color-foreground-primary, #141414);
    }

    .field--validating {
      --fsds-field-color-fg: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .field--valid {
      --fsds-field-color-fg: var(--fsds-semantic-color-foreground-success, #497f21);
    }

    .field--invalid {
      --fsds-field-color-fg: var(--fsds-semantic-color-foreground-danger, #d92d2e);
    }

    @layer components.defaults {
    .field {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-field-design-root-spacing-gap, var(--fsds-field-gap-y, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      display: flex;
      flex-direction: column;
    }

    .field__label {
      display: inline-block;
      font-size: var(--fsds-field-design-label-typography-size, var(--fsds-field-label-font-size, 14px));
      font-weight: var(--fsds-field-design-label-typography-weight, 500);
      color: var(--fsds-field-design-label-foreground-color, var(--fsds-field-label-color, #474647));
    }

    .field__header {
      display: flex;
      align-items: baseline;
      justify-content: space-between;
      gap: var(--fsds-field-design-header-spacing-gap, var(--fsds-field-gap-meta, 4px));
    }

    .field__control {
      display: flex;
      flex-direction: column;
      width: 100%;
      box-sizing: border-box;
    }

    .field__help {
      display: block;
      font-size: var(--fsds-field-design-help-typography-size, 0.875em);
      color: var(--fsds-field-design-help-foreground-color, var(--fsds-field-color-fg, #141414));
    }

    .field__error {
      display: block;
      font-size: var(--fsds-field-design-error-typography-size, 0.875em);
      color: var(--fsds-field-design-error-foreground-color, var(--fsds-field-color-invalid-text, #d92d2e));
    }

    .field__meta {
      display: flex;
      flex-direction: column;
      gap: var(--fsds-field-design-meta-spacing-gap, var(--fsds-field-gap-meta, 4px));
    }

    .field__validatingIndicator {
      display: inline-flex;
      width: 1em;
      height: 1em;
      color: var(--fsds-field-design-validating-indicator-foreground-color, var(--fsds-field-color-fg, #141414));
    }

    .field--disabled .field__header, .field--disabled .field__meta {
      opacity: 0.5;
    }
    }
  `;

  override render() {
    return html`<fsds-stack class="field__header"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-field-header', FieldHeaderElement);
// @generated:end

// @custom:start trailing

// @custom:end