import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { expect, it } from "vitest";
import type { ComponentContract } from "../contract.js";
import { buildComponentIR } from "../ir.js";
import { generateSwiftUIComponentSource } from "./swift/swiftui/component-source.js";
import { generateJetpackComposeComponentSource } from "./jetpack-compose/component-source.js";
import { generateReactNativeComponentSource } from "./react-native/component-source.js";

it("lowers a renamed annotated-source contract through native highlight facts", () => {
  const contract = JSON.parse(readFileSync(resolve(__dirname, "../../../ds-contracts/components/CodeBlock/CodeBlock.contract.json"), "utf8")) as ComponentContract;
  contract.name = "AnnotatedSource";
  const ir = buildComponentIR(contract);
  const swift = generateSwiftUIComponentSource(ir);
  expect(swift).toContain("public struct AnnotatedSource: View");
  expect(swift).toContain("public struct AnnotatedSourceLine<Content: View>: View");
  expect(swift).toContain("public struct CodeBlockToken: View");
  expect(swift).toContain('code: String = ""');
  expect(swift).toContain("SwiftUI.Text(verbatim: code)");
  expect(swift).toContain("tokens!.map(\\.text).joined() == code");
  const compose = generateJetpackComposeComponentSource(ir);
  expect(compose).toContain("code: String");
  expect(compose).toContain("content: (@Composable () -> Unit)? = null");
  expect(compose).toContain("fun AnnotatedSourceLine(");
  expect(compose).toContain("tokens.joinToString(\"\") { it.text } == code");
  expect(compose).toContain("if (content != null)");
  expect(compose).toContain('layeredSlot("box-model.min-height")?.toFsdsDp()');
  expect(compose).toContain("Modifier.heightIn(min = minHeight).clip(shape)");
  expect(compose.match(/modifier\.then\(chromeModifier\)/g)).toHaveLength(3);
  const native = JSON.stringify(generateReactNativeComponentSource(ir));
  expect(native).toContain("prepareSourceLines(code, suppliedTokens, highlight)");
  expect(native).toContain("showLineNumbers");
});
