extends SceneTree
const Budget = preload("res://addons/full_stack_ds/runtime/sequence_budget.gd")
var failures: Array[String] = []
var requests: Array[int] = []
func check(condition: bool, message: String) -> void:
	if not condition: failures.append(message)

func _initialize() -> void:
	var budget = Budget.new()
	budget.index_requested.connect(func(next: int): requests.append(next))
	budget.sync(0, ["A", "B", "C"], [1, 2, 3], 1000.0, true, 0.0)
	budget.tick(300.0)
	check(is_equal_approx(budget.elapsed(), 0.3), "elapsed projection")
	budget.pause("hover", 300.0)
	budget.pause("background", 400.0)
	budget.tick(5000.0)
	budget.resume("hover", 5000.0)
	budget.tick(6000.0)
	check(requests.is_empty() and is_equal_approx(budget.elapsed(), 0.3), "pause reasons must compose")
	budget.resume("background", 6000.0)
	budget.tick(6699.0)
	check(requests.is_empty(), "full remaining active dwell")
	budget.tick(6700.0)
	budget.tick(9900.0)
	check(requests == [1] and budget.pending, "one request before controlled acknowledgement")
	budget.stop(9900.0)
	budget.rotate(true, 9900.0)
	budget.tick(12000.0)
	check(requests == [1], "rotation cannot bypass acknowledgement")
	budget.sync(1, ["A", "B", "C"], [1, 2, 3], 1000.0, true, 12000.0)
	var old_owner: int = budget.begin_transition(12000.0)
	budget.request(0, 12050.0)
	budget.sync(0, ["A", "B", "C"], [1, 2, 3], 1000.0, true, 12050.0)
	var new_owner: int = budget.begin_transition(12050.0)
	budget.finish_transition(old_owner, 12100.0)
	budget.tick(15000.0)
	check(requests == [1, 0] and budget.remaining_ms == 1000.0, "stale motion completion cannot release a newer pause")
	budget.finish_transition(new_owner, 15000.0)
	budget.tick(15999.0)
	check(requests == [1, 0], "movement preserves the full incoming dwell")
	budget.tick(16000.0)
	check(requests == [1, 0, 1], "advance after movement plus dwell")
	budget.sync(1, ["A"], [1, 2, 3], 1000.0, true, 16000.0)
	budget.pause("touch", 16000.0)
	budget.sync(1, ["A", "B", "C"], [1, 2, 3], 1000.0, true, 17000.0)
	budget.tick(19000.0)
	check(requests == [1, 0, 1], "invalid composition does not erase touch pause")
	budget.destroy()
	budget.resume("touch", 20000.0)
	budget.request(2, 21000.0)
	budget.tick(25000.0)
	check(requests == [1, 0, 1], "destroyed budget cannot request")
	var duplicate = Budget.new()
	duplicate.sync(0, ["A", "B"], [1, 2], 1000.0, true, 0.0)
	duplicate.resume("background", 400.0)
	duplicate.tick(500.0)
	check(is_equal_approx(duplicate.elapsed(), 0.5), "redundant resume must account active time")
	duplicate.stop(500.0)
	duplicate.sync(0, ["A", "B"], [1, 2], 1000.0, false, 600.0)
	duplicate.sync(0, ["A", "B"], [1, 2], 1000.0, true, 700.0)
	check(not duplicate.playing, "autoplay prop cannot override focus stop")
	duplicate.rotate(true, 800.0)
	duplicate.tick(1000.0)
	check(is_equal_approx(duplicate.elapsed(), 0.7), "explicit start resumes remaining budget")
	print(JSON.stringify({"kind":"godot-sequence-budget", "passed":failures.is_empty(), "failures":failures, "version":Engine.get_version_info().string}))
	quit(0 if failures.is_empty() else 1)
