// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { ref } from 'lit/directives/ref.js';
import { PagedSetController } from "../../primitives/controllers/PagingController.js";
import { property } from 'lit/decorators.js';
import { PaginationBehavior } from './PaginationBehavior.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type PaginationPresentation = "indicators" | "pages";
export type PaginationProgress = "none" | "elapsed";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class PaginationElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .pagination {
      --fsds-pagination-color-foreground: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-pagination-color-track: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-pagination-spacing-gap: var(--fsds-core-spacing-size-04, 8px);
      --fsds-pagination-size-dot-size: var(--fsds-core-spacing-size-04, 8px);
      --fsds-pagination-size-active-size: var(--fsds-core-spacing-size-08, 32px);
      --fsds-pagination-size-radius: var(--fsds-core-shape-radius-full, 9999px);
      --fsds-pagination-color-on-current: var(--fsds-semantic-color-foreground-inverse, #fafafa);
      --fsds-pagination-color-current: var(--fsds-semantic-color-action-background-primary-default, #0566fe);
    }

    @layer components.defaults {
    .pagination {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-pagination-design-root-spacing-gap, var(--fsds-pagination-spacing-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      display: flex;
      align-items: center;
      color: var(--fsds-pagination-design-root-foreground-color, var(--fsds-pagination-color-foreground, #141414));
    }

    .pagination__item {
      position: relative;
      padding: var(--fsds-pagination-design-item-spacing-padding, 0);
      border: 0;
      cursor: pointer;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: var(--fsds-pagination-design-item-sizing-width, 24px);
      height: var(--fsds-pagination-design-item-sizing-height, 24px);
      background: transparent;
      font: inherit;
      color: var(--fsds-pagination-design-item-foreground-color, inherit);
    }

    .pagination__marker {
      width: var(--fsds-pagination-design-marker-sizing-width, var(--fsds-pagination-size-dot-size, 8px));
      height: var(--fsds-pagination-design-marker-sizing-height, var(--fsds-pagination-size-dot-size, 8px));
      border-radius: var(--fsds-pagination-design-marker-shape-radius, var(--fsds-pagination-size-radius, 9999px));
      overflow: hidden;
      background-color: var(--fsds-pagination-design-marker-background-fill, var(--fsds-pagination-color-track, #d0d0d0));
      display: block;
      position: relative;
    }

    .pagination__fill {
      position: absolute;
      inset: 0;
      background-color: var(--fsds-pagination-design-fill-background-fill, var(--fsds-pagination-color-foreground, #141414));
      transform-origin: left center;
      display: none;
    }

    .pagination__label {
      display: none;
    }

    .pagination--pages .pagination__label {
      display: inline;
    }

    .pagination--pages .pagination__marker {
      display: none;
    }

    .pagination--indicators .pagination__item[data-current="true"] .pagination__marker {
      width: var(--fsds-pagination-design-condition-aea309601ea3-sizing-width, var(--fsds-pagination-size-active-size, 32px));
    }

    .pagination--pages .pagination__item[data-current="true"] {
      background-color: var(--fsds-pagination-design-condition-a2b8c9e94dbf-background-fill, var(--fsds-pagination-color-current, #0566fe));
      color: var(--fsds-pagination-design-condition-a2b8c9e94dbf-foreground-color, var(--fsds-pagination-color-on-current, #fafafa));
    }

    .pagination__fill[hidden] {
      display: none !important;
    }

    .pagination--elapsed .pagination__fill {
      display: block;
    }

    .pagination--pages .pagination__item {
      width: var(--fsds-pagination-design-condition-d13042c5cc6d-sizing-width, auto);
      min-width: var(--fsds-pagination-design-condition-d13042c5cc6d-sizing-min-width, 24px);
      padding: var(--fsds-pagination-design-condition-d13042c5cc6d-spacing-padding, 4px 8px);
      border-radius: var(--fsds-pagination-design-condition-d13042c5cc6d-shape-radius, 4px);
    }

    .pagination__fill:dir(rtl) {
      transform-origin: right center;
    }
    }
  `;

  @property({ attribute: false }) pages?: string[] = [];
  @property({ type: Number }) index?: number;
  @property({ type: Number }) defaultIndex?: number = 0;
  @property({ attribute: false }) onIndexChange?: (index: number) => void;
  @property({ type: String }) presentation?: PaginationPresentation = "indicators";
  @property({ type: String }) label?: string = "Choose page";
  @property({ type: Boolean }) disabled?: boolean = false;
  @property({ type: String }) progress?: PaginationProgress = "none";

  private initializedBehavior?: PaginationBehavior;
  private get behavior(): PaginationBehavior {
    return this.initializedBehavior ??= new PaginationBehavior(this, {
    index: () => this.index,
    defaultIndex: this.defaultIndex,
    onIndexChange: (v) => this.onIndexChange?.(v),
  });
  }
  private pagedSet = new PagedSetController(this, () => ({ index: this.behavior.page, items: this.pages ?? [],
    count: undefined, disabled: this.disabled, onIndexChange: (value) => this.behavior.setPage(value) }));

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "pagination");
  }

  private computeClasses(): string {
    return [
      "pagination",
      (this.presentation ?? "indicators") ? `pagination--${(this.presentation ?? "indicators")}` : null,
      (this.progress ?? "none") ? `pagination--${(this.progress ?? "none")}` : null,
      (this.disabled ?? false) ? "pagination--disabled" : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}" role="group" aria-label=${ifDefined((this.label ?? "Choose page"))} data-fsds-box="">
  ${((this.pages ?? [])).map((item, index) => html`
  <button class=${'pagination__item'} type="button" @click=${() => this.pagedSet.request(index)} aria-label=${item} aria-current=${((index === this.behavior.page)) ? 'true' : 'false'} ?disabled=${(this.disabled ?? false)} data-current=${(index === this.behavior.page)}>
    <span class=${'pagination__marker'} aria-hidden="true">
      <span class=${'pagination__fill'} aria-hidden="true"></span>
    </span>
    <span class=${'pagination__label'} aria-hidden="true">${item}</span>
  </button>
  `)}
</div>`;
  }
}

customElements.define('fsds-pagination', PaginationElement);

// @generated:end

// @custom:start trailing

// @custom:end