// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property, state } from 'lit/decorators.js';
import { prepareHighlightSource } from '../../primitives/highlight/tokenize.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CodeBlockLanguage = "bash" | "css" | "html" | "javascript" | "json" | "jsx" | "markdown" | "plaintext" | "svelte" | "tsx" | "typescript" | "vue";
export type CodeBlockTokenType = "comment" | "definition" | "keyword" | "plain" | "property" | "punctuation" | "static" | "string" | "tag";
export type CodeBlockToken = { kind: CodeBlockTokenType; text: string };
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class CodeBlockLineElement extends LitElement {
  static override styles = css`
    :host { display: inline; white-space: pre; }
    .code-block__gutter { display: none; user-select: none; }
    .code-block__gutter::before { content: attr(data-line); }
    :host([show-line-numbers]) .code-block__gutter { display: inline-block; min-width: 2ch; text-align: right; margin-right: var(--fsds-code-block-gutter-size-gap, 4px); color: var(--fsds-code-block-gutter-color-number, #474647); }
  `;
  @property({ type: Number }) number = 1;
  @property({ type: String }) ending = "";
  @property({ type: Boolean, attribute: "show-line-numbers" }) showLineNumbers = false;
  override render() { return html`<span class="code-block__line"><span class="code-block__gutter" data-line=${this.number} aria-hidden="true"></span><slot></slot>${this.ending}</span>`; }
}
customElements.define('fsds-code-block-line', CodeBlockLineElement);

export class CodeBlockTokenElement extends LitElement {
  static override styles = css`
    .code-block__token[data-token="comment"] { color: var(--fsds-code-block-token-color-comment, #474647); }
    .code-block__token[data-token="definition"] { color: var(--fsds-code-block-token-color-definition, #900909); }
    .code-block__token[data-token="keyword"] { color: var(--fsds-code-block-token-color-keyword, #013ab0); }
    .code-block__token[data-token="plain"] { color: var(--fsds-code-block-token-color-plain, #141414); }
    .code-block__token[data-token="property"] { color: var(--fsds-code-block-token-color-property, #6c3a00); }
    .code-block__token[data-token="punctuation"] { color: var(--fsds-code-block-token-color-punctuation, #013ab0); }
    .code-block__token[data-token="static"] { color: var(--fsds-code-block-token-color-static, #900909); }
    .code-block__token[data-token="string"] { color: var(--fsds-code-block-token-color-string, #900909); }
    .code-block__token[data-token="tag"] { color: var(--fsds-code-block-token-color-tag, #900909); }
  `;
  @property({ type: String, attribute: "data-token", reflect: true }) kind: CodeBlockTokenType = "plain";
  override render() { return html`<span class="code-block__token" data-token=${this.kind}><slot></slot></span>`; }
}
customElements.define('fsds-code-block-token', CodeBlockTokenElement);

export class CodeBlockElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .code-block {
      --fsds-code-block-color-background: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-code-block-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-code-block-color-border: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-code-block-size-padding: var(--fsds-core-spacing-size-06, 16px);
      --fsds-code-block-size-radius: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-code-block-size-border: var(--fsds-semantic-shape-control-border-default-width, 1px);
      --fsds-code-block-size-font-size: var(--fsds-core-typography-ramp-3, 0.875rem);
      --fsds-code-block-typography-line-height: var(--fsds-semantic-typography-line-height-body, 1.5);
      --fsds-code-block-token-color-plain: var(--fsds-semantic-color-foreground-syntax-plain, #141414);
      --fsds-code-block-token-color-comment: var(--fsds-semantic-color-foreground-syntax-comment-color, #474647);
      --fsds-code-block-token-color-keyword: var(--fsds-semantic-color-foreground-syntax-keyword, #013ab0);
      --fsds-code-block-token-color-definition: var(--fsds-semantic-color-foreground-syntax-definition, #900909);
      --fsds-code-block-token-color-punctuation: var(--fsds-semantic-color-foreground-syntax-punctuation, #013ab0);
      --fsds-code-block-token-color-property: var(--fsds-semantic-color-foreground-syntax-property, #6c3a00);
      --fsds-code-block-token-color-static: var(--fsds-semantic-color-foreground-syntax-static, #900909);
      --fsds-code-block-token-color-string: var(--fsds-semantic-color-foreground-syntax-string, #900909);
      --fsds-code-block-token-color-tag: var(--fsds-semantic-color-foreground-syntax-tag, #900909);
      --fsds-code-block-gutter-color-number: var(--fsds-semantic-color-foreground-secondary, #474647);
      --fsds-code-block-gutter-size-gap: var(--fsds-core-spacing-size-03, 4px);
    }

    @layer components.defaults {
    .code-block {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-surface-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-surface-size-padding-inline, 16px));
      gap: var(--fsds-box-model-gap, var(--fsds-semantic-display-size-gap, 4px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      background-color: var(--fsds-code-block-design-root-background-fill, var(--fsds-code-block-color-background, #f7f7f7));
      border-color: var(--fsds-code-block-design-root-border-color, var(--fsds-code-block-color-border, #d0d0d0));
      border-style: var(--fsds-code-block-design-root-border-style, solid);
      border-width: var(--fsds-code-block-design-root-border-width, var(--fsds-code-block-size-border, 1px));
      border-radius: var(--fsds-code-block-design-root-shape-radius, var(--fsds-code-block-size-radius, 6px));
      color: var(--fsds-code-block-design-root-foreground-color, var(--fsds-code-block-color-foreground-primary, #141414));
      font-family: var(--fsds-code-block-design-root-typography-family, var(--fsds-semantic-typography-semantic-family-mono, "Monaspace", ui-monospace, SFMono-Regular, Menlo, monospace));
      font-size: var(--fsds-code-block-design-root-typography-size, var(--fsds-code-block-size-font-size, 0.875rem));
      line-height: var(--fsds-code-block-design-root-typography-line-height, var(--fsds-code-block-typography-line-height, 1.5));
      margin: 0;
      overflow-x: auto;
      padding: var(--fsds-code-block-design-root-spacing-padding, var(--fsds-code-block-size-padding, 16px));
      tab-size: 2;
      white-space: pre;

      &[data-line-numbers="true"] .code-block__gutter {
        display: inline-block;
        min-width: 4ch;
        padding-inline-end: var(--fsds-code-block-design-condition-37b3a6622954-spacing-padding-inline-end, var(--fsds-code-block-gutter-size-gap, 4px));
        color: var(--fsds-code-block-design-condition-37b3a6622954-foreground-color, var(--fsds-code-block-gutter-color-number, #474647));
        text-align: var(--fsds-code-block-design-condition-37b3a6622954-typography-alignment, right);
        user-select: none;
      }
    }

    .code-block__code {
      display: block;
      font-family: var(--fsds-code-block-design-code-typography-family, inherit);
      font-size: var(--fsds-code-block-design-code-typography-size, inherit);
    }

    .code-block__line {
      white-space: pre;
    }

    .code-block__gutter {
      display: none;
    }

    .code-block__gutter::before {
      content: attr(data-line);
    }

    .code-block__token[data-token="plain"] {
      color: var(--fsds-code-block-design-condition-b26259dbe6d6-foreground-color, var(--fsds-code-block-token-color-plain, #141414));
    }

    .code-block__token[data-token="comment"] {
      color: var(--fsds-code-block-design-condition-8d8c610b44f8-foreground-color, var(--fsds-code-block-token-color-comment, #474647));
    }

    .code-block__token[data-token="keyword"] {
      color: var(--fsds-code-block-design-condition-4b23b87f0ae5-foreground-color, var(--fsds-code-block-token-color-keyword, #013ab0));
    }

    .code-block__token[data-token="definition"] {
      color: var(--fsds-code-block-design-condition-e64795b05064-foreground-color, var(--fsds-code-block-token-color-definition, #900909));
    }

    .code-block__token[data-token="punctuation"] {
      color: var(--fsds-code-block-design-condition-6acac665cbb0-foreground-color, var(--fsds-code-block-token-color-punctuation, #013ab0));
    }

    .code-block__token[data-token="property"] {
      color: var(--fsds-code-block-design-condition-bb5556a6dabf-foreground-color, var(--fsds-code-block-token-color-property, #6c3a00));
    }

    .code-block__token[data-token="static"] {
      color: var(--fsds-code-block-design-condition-460d112a4b91-foreground-color, var(--fsds-code-block-token-color-static, #900909));
    }

    .code-block__token[data-token="string"] {
      color: var(--fsds-code-block-design-condition-02a586e46f1c-foreground-color, var(--fsds-code-block-token-color-string, #900909));
    }

    .code-block__token[data-token="tag"] {
      color: var(--fsds-code-block-design-condition-106897d75995-foreground-color, var(--fsds-code-block-token-color-tag, #900909));
    }
    }
  `;

  @property({ type: String }) code!: string;
  @property({ type: String }) language!: CodeBlockLanguage;
  @property({ type: Boolean }) highlight?: boolean = true;
  @property({ attribute: false }) tokens?: CodeBlockToken[];
  @property({ type: Boolean }) showLineNumbers?: boolean = false;

  // Tracks whether any content has been slotted in — used by the
  // conditional label wrapper (if: "children" in the contract dom tree).
  @state() private _hasChildren = false;

  override firstUpdated(): void {
    const slot = this.shadowRoot?.querySelector('slot:not([name])') as HTMLSlotElement | null;
    if (slot) {
      const update = () => { this._hasChildren = slot.assignedNodes({ flatten: true }).some(node => node.nodeType === Node.ELEMENT_NODE || (node.nodeType === Node.TEXT_NODE && node.textContent !== "")); };
      slot.addEventListener('slotchange', update);
      update();
    }
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "code-block");
  }

  private computeClasses(): string {
    return [
      "code-block",
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<pre class="${this.computeClasses()}" data-language=${ifDefined(this.language)} ?data-line-numbers=${(this.showLineNumbers ?? false)} data-fsds-box=""><code class=${'code-block__code'} spellcheck="false" data-language=${ifDefined(this.language)}><slot></slot>${!this._hasChildren ? html`<span class=${'code-block__source'}>${prepareHighlightSource(this.code, this.language, { tokens: this.tokens, highlight: (this.highlight ?? true) }).lines.map((line) => html`<fsds-code-block-line .number=${line.number} ?show-line-numbers=${(this.showLineNumbers ?? false)}>${line.tokens.map((token) => line.highlighted ? html`<fsds-code-block-token .kind=${token.kind} data-token=${token.kind}>${token.text}</fsds-code-block-token>` : token.text)}</fsds-code-block-line>${line.ending}`)}</span>` : nothing}</code></pre>`;
  }
}

customElements.define('fsds-code-block', CodeBlockElement);

// @generated:end

// @custom:start trailing

// @custom:end