import type { ComponentIR, HighlightTransformIR } from "../../ir.js";
import { highlightTokenTypes } from "../../highlight/token-types.js";

/** Compose realization of the framework-neutral supplied-source transform. */
export function emitComposeHighlightComponent(ir: ComponentIR, transform: HighlightTransformIR): string {
  const name = ir.name;
  const segment = name.toLowerCase();
  const tokenScopes = `${name.charAt(0).toLowerCase()}${name.slice(1)}TokenScopes`;
  const { tokenName, kindName: tokenType } = highlightTokenTypes(ir, transform);
  const lineName = `${name}${transform.linePart!.charAt(0).toUpperCase()}${transform.linePart!.slice(1)}`;
  const prefix = ir.cssPrefix;
  const palette = ir.definedTypes[tokenType];
  if (palette?.kind !== "union" || !palette.values) throw new Error(`${name}: highlight token kinds require a union`);
  const enumValue = (value: string) => value.charAt(0).toUpperCase() + value.slice(1);
  const enumCases = palette.values.map((kind) => `    ${enumValue(kind)}(${JSON.stringify(kind)}),`).join("\n");
  const paletteCases = palette.values.map((kind) => `        ${tokenType}.${enumValue(kind)} -> layeredSlot(${JSON.stringify(`${prefix}.${transform.tokenPart}.color.${kind}`)})?.toFsdsColor()`).join("\n");

  return String.raw`// @generated by ds-codegen from components/${name}/${name}.contract.json — do not edit by hand.
package com.fullstackds.components.${segment}

// @generated:start imports
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.widthIn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicText
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import com.fullstackds.tokens.LocalFsdsContentColor
import com.fullstackds.tokens.LocalFsdsTheme
import com.fullstackds.tokens.toFsdsColor
import com.fullstackds.tokens.toFsdsDp
import com.fullstackds.tokens.toFsdsSp
// @generated:end

// @generated:start component
enum class ${tokenType}(val wire: String) {
${enumCases}
}

data class ${tokenName}(val kind: ${tokenType}, val text: String)

@Composable
fun ${tokenName}(token: ${tokenName}, modifier: Modifier = Modifier, style: TextStyle = TextStyle.Default) {
    val fsdsTheme = LocalFsdsTheme.current
    fun layeredSlot(slotName: String): String? = ${tokenScopes}["root"]?.get(slotName)?.let { fsdsTheme.resolve(it) }
    val tokenColor = when (token.kind) {
${paletteCases}
    }
    BasicText(token.text, modifier = modifier, style = style.copy(color = tokenColor ?: style.color))
}

@Composable
fun ${lineName}(number: Int, showLineNumbers: Boolean = false, modifier: Modifier = Modifier, content: @Composable () -> Unit) {
    val fsdsTheme = LocalFsdsTheme.current
    fun layeredSlot(slotName: String): String? = ${tokenScopes}["root"]?.get(slotName)?.let { fsdsTheme.resolve(it) }
    val gutterColor = layeredSlot("${prefix}.${transform.gutterPart}.color.number")?.toFsdsColor() ?: Color.Unspecified
    val gutterGap = layeredSlot("${prefix}.${transform.gutterPart}.size.gap")?.toFsdsDp() ?: 0.dp
    Row(modifier = modifier, verticalAlignment = Alignment.Top) {
        if (showLineNumbers) {
            BasicText(
                number.toString(),
                modifier = Modifier.widthIn(min = 28.dp).padding(end = gutterGap).clearAndSetSemantics { },
                style = TextStyle(color = gutterColor, textAlign = TextAlign.End),
            )
        }
        content()
    }
}

internal data class FsdsSourceLine(val tokens: List<${tokenName}>)

internal fun fsdsSplitSource(code: String, tokens: List<${tokenName}>?, highlight: Boolean): Pair<List<FsdsSourceLine>, Boolean> {
    val valid = highlight && tokens != null && tokens.joinToString("") { it.text } == code
    val stream = if (valid) tokens!! else listOf(${tokenName}(${tokenType}.Plain, code))
    val lines = mutableListOf<FsdsSourceLine>()
    var current = mutableListOf<${tokenName}>()
    val text = StringBuilder()
    var kind: ${tokenType}? = null
    var skipLF = false
    fun flushToken() {
        if (text.isNotEmpty()) current.add(${tokenName}(kind!!, text.toString()))
        text.clear()
    }
    fun flushLine() {
        flushToken()
        kind = null
        lines.add(FsdsSourceLine(current))
        current = mutableListOf()
    }
    for (token in stream) {
        for (character in token.text) {
            if (skipLF) {
                skipLF = false
                if (character == '\n') continue
            }
            if (character == '\r' || character == '\n') {
                flushLine()
                skipLF = character == '\r'
                continue
            }
            if (kind != token.kind) {
                flushToken()
                kind = token.kind
            }
            text.append(character)
        }
    }
    flushLine()
    return Pair(lines, valid)
}

@Composable
fun ${name}(
    ${transform.sourceProp}: String,
    modifier: Modifier = Modifier,
    ${transform.tokensProp}: List<${tokenName}>? = null,
    ${transform.gateProp}: Boolean = true,
    ${transform.lineNumbersProp}: Boolean = false,
    content: (@Composable () -> Unit)? = null,
) {
    val fsdsTheme = LocalFsdsTheme.current
    fun layeredSlot(slotName: String): String? = ${tokenScopes}["root"]?.get(slotName)?.let { fsdsTheme.resolve(it) }
    val containerColor = layeredSlot("${prefix}.color.background.default")?.toFsdsColor()
    val contentColor = layeredSlot("${prefix}.color.foreground.primary")?.toFsdsColor()
    val cornerRadius = layeredSlot("${prefix}.size.radius.default")?.toFsdsDp() ?: 0.dp
    val paddingInlineStart = layeredSlot("box-model.padding-inline-start")?.toFsdsDp() ?: 0.dp
    val paddingInlineEnd = layeredSlot("box-model.padding-inline-end")?.toFsdsDp() ?: 0.dp
    val paddingBlockStart = layeredSlot("box-model.padding-block-start")?.toFsdsDp() ?: 0.dp
    val paddingBlockEnd = layeredSlot("box-model.padding-block-end")?.toFsdsDp() ?: 0.dp
    val fsdsFontSize = layeredSlot("${prefix}.size.fontSize.default")?.toFsdsSp()
    val shape = RoundedCornerShape(cornerRadius)
    val chromeModifier = Modifier.clip(shape)
        .then(if (containerColor != null) Modifier.background(containerColor, shape) else Modifier)
        .padding(start = paddingInlineStart, end = paddingInlineEnd, top = paddingBlockStart, bottom = paddingBlockEnd)
    val sourceStyle = TextStyle(fontSize = fsdsFontSize ?: TextUnit.Unspecified, color = contentColor ?: Color.Unspecified)
    if (content != null) {
        CompositionLocalProvider(LocalFsdsContentColor provides (contentColor ?: Color.Unspecified)) {
            Box(modifier.then(chromeModifier)) { content() }
        }
    } else {
        val (lines, highlighted) = fsdsSplitSource(${transform.sourceProp}, ${transform.tokensProp}, ${transform.gateProp})
        if (!${transform.lineNumbersProp} && !highlighted) {
            BasicText(${transform.sourceProp}, modifier = modifier.then(chromeModifier), style = sourceStyle)
        } else {
            Column(modifier.then(chromeModifier).clearAndSetSemantics { contentDescription = ${transform.sourceProp} }) {
                lines.forEachIndexed { index, line ->
                    ${lineName}(number = index + 1, showLineNumbers = ${transform.lineNumbersProp}) {
                        Row {
                            line.tokens.forEach { token ->
                                if (highlighted) ${tokenName}(token, style = sourceStyle)
                                else BasicText(token.text, style = sourceStyle)
                            }
                        }
                    }
                }
            }
        }
    }
}
// @generated:end
`;
}
