// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { ref } from 'lit/directives/ref.js';
import { SequenceController } from "../../primitives/controllers/SequenceController.js";
import { property } from 'lit/decorators.js';
import '../Icon/Icon.js';
import '../Pagination/Pagination.js';
import { CarouselBehavior } from './CarouselBehavior.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type CarouselIndicator = "pagination" | "next" | "both";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class CarouselElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .carousel {
      --fsds-carousel-color-foreground: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-carousel-color-progress: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-carousel-spacing-gap: var(--fsds-core-spacing-size-04, 8px);
      --fsds-carousel-size-control-size: var(--fsds-core-spacing-size-08, 32px);
      --fsds-carousel-size-radius: var(--fsds-core-shape-radius-full, 9999px);
    }

    @layer components.defaults {
    .carousel {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-carousel-design-root-spacing-gap, var(--fsds-carousel-spacing-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      display: flex;
      flex-direction: column;
      color: var(--fsds-carousel-design-root-foreground-color, var(--fsds-carousel-color-foreground, #141414));

      &:not([data-sequence-root]) > .carousel__viewport {
        visibility: hidden;
      }
    }

    .carousel__viewport {
      min-width: 0;
      position: relative;
      overflow: hidden;
    }

    .carousel__viewport > [hidden] {
      display: none !important;
    }

    .carousel__controls {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: var(--fsds-carousel-design-controls-spacing-gap, var(--fsds-carousel-spacing-gap, 8px));
    }

    .carousel__ring {
      position: absolute;
      inset: -4px;
      border-radius: var(--fsds-carousel-design-ring-shape-radius, 50%);
      background: conic-gradient(currentColor calc(var(--sequence-progress, 0) * 1turn), transparent 0);
      mask: radial-gradient(farthest-side, transparent calc(100% - 2px), #000 0);
      color: var(--fsds-carousel-design-ring-foreground-color, var(--fsds-carousel-color-progress, #141414));
      pointer-events: none;
      display: none;
    }

    .carousel [hidden] {
      display: none !important;
    }

    .carousel__next {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      position: relative;
      min-width: var(--fsds-carousel-design-next-sizing-min-width, var(--fsds-carousel-size-control-size, 32px));
      min-height: var(--fsds-carousel-design-next-sizing-min-height, var(--fsds-carousel-size-control-size, 32px));
      border: 1px solid currentColor;
      border-radius: var(--fsds-carousel-design-next-shape-radius, var(--fsds-carousel-size-radius, 9999px));
      background: transparent;
      color: var(--fsds-carousel-design-next-foreground-color, inherit);
      cursor: pointer;
    }

    .carousel__previous {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      position: relative;
      min-width: var(--fsds-carousel-design-previous-sizing-min-width, var(--fsds-carousel-size-control-size, 32px));
      min-height: var(--fsds-carousel-design-previous-sizing-min-height, var(--fsds-carousel-size-control-size, 32px));
      border: 1px solid currentColor;
      border-radius: var(--fsds-carousel-design-previous-shape-radius, var(--fsds-carousel-size-radius, 9999px));
      background: transparent;
      color: var(--fsds-carousel-design-previous-foreground-color, inherit);
      cursor: pointer;
    }

    .carousel__rotation {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      position: relative;
      min-width: var(--fsds-carousel-design-rotation-sizing-min-width, var(--fsds-carousel-size-control-size, 32px));
      min-height: var(--fsds-carousel-design-rotation-sizing-min-height, var(--fsds-carousel-size-control-size, 32px));
      border: 1px solid currentColor;
      border-radius: var(--fsds-carousel-design-rotation-shape-radius, var(--fsds-carousel-size-radius, 9999px));
      background: transparent;
      color: var(--fsds-carousel-design-rotation-foreground-color, inherit);
      cursor: pointer;
      align-self: flex-start;
      padding-inline: var(--fsds-carousel-design-rotation-spacing-padding-inline, 12px);
      font: inherit;
    }

    .carousel--next .carousel__ring, .carousel--both .carousel__ring {
      display: block;
    }
    }
  `;

  @property({ attribute: false }) slides?: string[] = [];
  @property({ type: Number }) index?: number;
  @property({ type: Number }) defaultIndex?: number = 0;
  @property({ attribute: false }) onIndexChange?: (index: number) => void;
  @property({ type: Boolean }) autoPlay?: boolean = false;
  @property({ attribute: false }) duration?: number | null;
  @property({ type: String }) indicator?: CarouselIndicator = "pagination";
  @property({ type: String }) label?: string = "Featured content";

  private initializedBehavior?: CarouselBehavior;
  private get behavior(): CarouselBehavior {
    return this.initializedBehavior ??= new CarouselBehavior(this, {
    index: () => this.index,
    defaultIndex: this.defaultIndex,
    onIndexChange: (v) => this.onIndexChange?.(v),
  });
  }
  private sequence = new SequenceController(this, {"labels":{"start":"Start slide rotation","stop":"Stop slide rotation","item":"slide"},"delegatedPicker":false,"transition":{"durationMs":250,"easing":"cubic-bezier(0.4, 0, 0.2, 1)","referenceWidth":320,"minMultiplier":0.5,"maxMultiplier":2},"parts":{"viewport":".carousel__viewport","previous":".carousel__previous","next":".carousel__next","rotation":".carousel__rotation","picker":".carousel__pagination .pagination__item"},"progress":[{"selector":".carousel__pagination .pagination__fill","effect":"elapsed-width","steps":10},{"selector":".carousel__ring","effect":"elapsed-ring","steps":10}]}, () => ({
    index: this.behavior.slide, labels: this.slides ?? [], autoPlay: this.autoPlay ?? false,
    durationMs: this.duration === undefined ? 6000 : this.duration,
    onIndexChange: (value) => this.behavior.setSlide(value),
  }));

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "carousel");
  }

  private computeClasses(): string {
    return [
      "carousel",
      (this.indicator ?? "pagination") ? `carousel--${(this.indicator ?? "pagination")}` : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<section class="${this.computeClasses()}" role="region" aria-roledescription="carousel" aria-label=${ifDefined((this.label ?? "Featured content"))} data-fsds-box="" ${ref(this.sequence.bindRoot)}>
  <button class=${'carousel__rotation'} type="button" aria-label="Start slide rotation">Start slide rotation</button>
  <div class=${'carousel__viewport'} aria-live="off" aria-atomic="false">
    <slot></slot>
  </div>
  <div class=${'carousel__controls'}>
    <button class=${'carousel__previous'} type="button" aria-label="Previous slide">
      <fsds-icon name="arrow-left" size="sm"></fsds-icon>
    </button>
    <fsds-pagination class=${'carousel__pagination'} label="Choose slide" presentation="indicators" .onIndexChange=${this.sequence.requestIndex} .pages=${(this.slides ?? [])} .index=${this.behavior.slide} .progress=${((this.indicator ?? "pagination") === "pagination" ? "elapsed" : ((this.indicator ?? "pagination") === "next" ? "none" : "elapsed"))}></fsds-pagination>
    <button class=${'carousel__next'} type="button" aria-label="Next slide">
      <span class=${'carousel__ring'} aria-hidden="true"></span>
      <fsds-icon name="arrow-right" size="sm"></fsds-icon>
    </button>
  </div>
</section>`;
  }
}

customElements.define('fsds-carousel', CarouselElement);

// @generated:end

// @custom:start trailing

// @custom:end