// Generated from Divider normalized contract IR. Do not hand-edit.
use std::collections::BTreeMap;
use gpui::{prelude::*,div,Context,SharedString,Window,FocusHandle};

use crate::style::{StyleRule,StyleCondition,StyleDeclaration,StyleState,Theme,ResolvedPartStyle,StyleError,resolve_part_style,apply_part_style,apply_interaction_style};
pub struct Divider{pub label:SharedString,pub theme:Theme,pub focused:bool,pub variant_values:BTreeMap<&'static str,SharedString>,pub focus_handle:Option<FocusHandle>,}
impl Default for Divider{fn default()->Self {let mut variants=BTreeMap::new();variants.insert("orientation","".into());Self{label:SharedString::default(),theme:Theme::default(),focused:false,variant_values:variants,focus_handle:None,}}}
impl Divider{
 pub const STYLE_RULES:&'static [StyleRule]=&[StyleRule {part:"root",conditions:&[],declarations:&[StyleDeclaration {property:"box-model.padding",value:"0",token:None},StyleDeclaration {property:"box-model.padding-block",value:"0",token:None},StyleDeclaration {property:"box-model.padding-block-start",value:"0",token:None},StyleDeclaration {property:"box-model.padding-block-end",value:"0",token:None},StyleDeclaration {property:"box-model.padding-inline",value:"0",token:None},StyleDeclaration {property:"box-model.padding-inline-start",value:"0",token:None},StyleDeclaration {property:"box-model.padding-inline-end",value:"0",token:None},StyleDeclaration {property:"box-model.gap",value:"4px",token:Some("semantic.display.size.gap")},StyleDeclaration {property:"box-model.width",value:"auto",token:None},StyleDeclaration {property:"box-model.min-width",value:"0",token:None},StyleDeclaration {property:"box-model.max-width",value:"none",token:None},StyleDeclaration {property:"box-model.height",value:"auto",token:None},StyleDeclaration {property:"box-model.min-height",value:"0",token:None},StyleDeclaration {property:"box-model.max-height",value:"none",token:None},StyleDeclaration {property:"divider.color",value:"#b8b8b8",token:Some("semantic.color.border.light")},StyleDeclaration {property:"divider.size.thickness",value:"1px",token:Some("semantic.shape.control.border.defaultWidth")},StyleDeclaration {property:"divider.spacing.margin",value:"8px",token:Some("core.spacing.size.04")}]},
StyleRule {part:"root",conditions:&[],declarations:&[StyleDeclaration {property:"padding",value:"0",token:Some("box-model.padding")},StyleDeclaration {property:"padding-block",value:"0",token:Some("box-model.padding-block")},StyleDeclaration {property:"padding-block-start",value:"0",token:Some("box-model.padding-block-start")},StyleDeclaration {property:"padding-block-end",value:"0",token:Some("box-model.padding-block-end")},StyleDeclaration {property:"padding-inline",value:"0",token:Some("box-model.padding-inline")},StyleDeclaration {property:"padding-inline-start",value:"0",token:Some("box-model.padding-inline-start")},StyleDeclaration {property:"padding-inline-end",value:"0",token:Some("box-model.padding-inline-end")},StyleDeclaration {property:"gap",value:"4px",token:Some("box-model.gap")},StyleDeclaration {property:"min-width",value:"0",token:Some("box-model.min-width")},StyleDeclaration {property:"min-height",value:"0",token:Some("box-model.min-height")}]},
StyleRule {part:"root",conditions:&[],declarations:&[StyleDeclaration {property:"display",value:"block",token:None},StyleDeclaration {property:"width",value:"100%",token:None},StyleDeclaration {property:"border-right-style",value:"none",token:None},StyleDeclaration {property:"divider.design.root.border.bottom.style",value:"none",token:None},StyleDeclaration {property:"border-bottom-style",value:"none",token:Some("divider.design.root.border.bottom.style")},StyleDeclaration {property:"border-left-style",value:"none",token:None},StyleDeclaration {property:"divider.design.root.border.top.color",value:"#b8b8b8",token:Some("divider.color")},StyleDeclaration {property:"border-top-color",value:"#b8b8b8",token:Some("divider.design.root.border.top.color")},StyleDeclaration {property:"divider.design.root.border.top.style",value:"solid",token:None},StyleDeclaration {property:"border-top-style",value:"solid",token:Some("divider.design.root.border.top.style")},StyleDeclaration {property:"divider.design.root.border.top.width",value:"1px",token:Some("divider.size.thickness")},StyleDeclaration {property:"border-top-width",value:"1px",token:Some("divider.design.root.border.top.width")},StyleDeclaration {property:"margin-top",value:"8px",token:Some("divider.spacing.margin")},StyleDeclaration {property:"margin-bottom",value:"8px",token:Some("divider.spacing.margin")}]},
StyleRule {part:"root",conditions:&[StyleCondition::Variant {axis:"orientation",value:"vertical"}],declarations:&[StyleDeclaration {property:"width",value:"1px",token:None},StyleDeclaration {property:"height",value:"auto",token:None},StyleDeclaration {property:"align-self",value:"stretch",token:None},StyleDeclaration {property:"min-height",value:"1em",token:None},StyleDeclaration {property:"border-top",value:"none",token:None},StyleDeclaration {property:"border-left-color",value:"#b8b8b8",token:Some("divider.color")},StyleDeclaration {property:"border-left-style",value:"solid",token:None},StyleDeclaration {property:"border-left-width",value:"1px",token:Some("divider.size.thickness")},StyleDeclaration {property:"margin-top",value:"0",token:None},StyleDeclaration {property:"margin-bottom",value:"0",token:None},StyleDeclaration {property:"margin-left",value:"8px",token:Some("divider.spacing.margin")},StyleDeclaration {property:"margin-right",value:"8px",token:Some("divider.spacing.margin")}]}];
 pub fn label(mut self,value:impl Into<SharedString>)->Self{self.label=value.into();self}
 pub fn set_label(&mut self,value:impl Into<SharedString>,cx:&mut Context<Self>){self.label=value.into();cx.notify();}
 pub fn theme(mut self,value:Theme)->Self{self.theme=value;self}
 pub fn set_theme(&mut self,value:Theme,cx:&mut Context<Self>){self.theme=value;cx.notify();}
 pub fn resolved_style(&self,part:&str)->Result<ResolvedPartStyle,StyleError>{
  let variants:Vec<(&str,&str)>=self.variant_values.iter().map(|(axis,value)|(*axis,value.as_ref())).collect();
  let state=StyleState{variants:&variants,checked:false,disabled:false,indeterminate:false,hovered:false,active:false,focused:self.focused};
  resolve_part_style(part,Self::STYLE_RULES,&state,&self.theme)
 }
 pub fn orientation(mut self,value:impl Into<SharedString>)->Self {let value=value.into();assert!(["horizontal","vertical"].contains(&value.as_ref()),"unsupported orientation variant");self.variant_values.insert("orientation",value);self}
pub fn set_orientation(&mut self,value:impl Into<SharedString>,cx:&mut Context<Self>){let value=value.into();assert!(["horizontal","vertical"].contains(&value.as_ref()),"unsupported orientation variant");self.variant_values.insert("orientation",value);cx.notify();}


}

impl Render for Divider{fn render(&mut self,window:&mut Window,_cx:&mut Context<Self>)->impl IntoElement{

 let variants:Vec<(&str,&str)>=self.variant_values.iter().map(|(axis,value)|(*axis,value.as_ref())).collect();
 self.theme.rem_size_px=f32::from(window.rem_size());self.theme.inherited_font_size_px=f32::from(window.text_style().font_size.to_pixels(window.rem_size()));let theme=self.theme.clone();
 self.focused=self.focus_handle.as_ref().map(|handle|handle.is_focused(window)).unwrap_or(false);
 let style_state=StyleState{variants:&variants,checked:false,disabled:false,indeterminate:false,hovered:false,active:false,focused:self.focused};
 let root=apply_part_style(div(),"root",Self::STYLE_RULES,&style_state,&theme).debug_selector(||"divider-root".to_string()).id("divider");
 let root=apply_interaction_style(root,"root",Self::STYLE_RULES,&style_state,&theme);

 root
}}
